### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jlew715/rails_proj1#1]
:+1: Looking really good! I looked around pretty hard for room for improvement, but couldn't really find anything apart from a typo where [this line is double-indented](https://github.com/jlew715/rails_proj1/blob/master/app/assets/stylesheets/static.scss#L68). I'm not going to make you fix that, but in case you're curious about SCSS, here is how part of your CSS could be rewritten its nested syntax:

``` scss
#nav {
  margin:0;
  padding:0;
  background-color:#000000;

  ul {
    margin:0;
    padding:0;
    list-style-type: none;
    text-align:center;
    width:100%;
    font-size:2em;
  }

  li {
    padding:0;
    margin:0;
    width:32%;
    display:inline-block;
    border-style:solid;
    border-width:1px;
    border-color:#FFFFFF;
  }

  a {
    padding:0;
    margin:0;
    color:#FFFFFF;
    text-decoration: none;

    &:hover {
      text-decoration: underline;
    }
  }
}
```

For comparison, here's the original:

``` css
#nav {
  margin:0;
  padding:0;
  background-color:#000000;
}

#nav ul {
  margin:0;
  padding:0;
  list-style-type: none;
  text-align:center;
  width:100%;
  font-size:2em;
}

#nav li {
  padding:0;
  margin:0;
  width:32%;
  display:inline-block;
  border-style:solid;
  border-width:1px;
  border-color:#FFFFFF;
}

#nav a {
  padding:0;
  margin:0;
  color:#FFFFFF;
  text-decoration: none;
}

#nav a:hover {
  text-decoration: underline;
}
```
